### ISSUE TITLE
computation of vectorfield: issue with loop for averaging

### ISSUE THREAD

**Issue by walkernoreen** [Biomedical-Imaging-Group/OrientationJ#1]
Hi,
There might be a small mistake in how the vector field is computed [here](https://github.com/Biomedical-Imaging-Group/OrientationJ/blob/master/src/main/java/orientation/OrientationResults.java) in displayVectorField, line 323ff. Should the following lines not use getPixel(x+l,y+k,t) instead of (x,y,t), otherwise nothing is averaged?

> 		for (int k = 0; k < size; k++)		
> 		for (int l = 0; l < size; l++) {
> 				double angle = gim.orientation.getPixel(x, y, t);
> 				double coh = gim.coherency.getPixel(x, y, t);
> 				dx += Math.cos(angle);
> 				dy += Math.sin(angle);
> 				coherencies += coh;
> 				energies += gim.energy.getPixel(x, y,t);
> 				}

And further down, the overlay lines should be displayed at c.x + size / 2 (as is stored in the table) instead of c.x?
I looked into the code into the context of [that](https://forum.image.sc/t/running-orientationj-vector-field-from-macro/23746) issue that I encountered, to avoid confusion about double posting

**Comment by dasv74** [comment]
Thank for your bug report.

The 2 above mentioned bugs have been fixed. The plugin and source are updated in Github, on Fiji, and on the webpage: http://bigwww.epfl.ch/demo/orientation/
